# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('cpf', models.CharField(max_length=14, verbose_name='cpf')),
                ('telefone', models.CharField(max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('matricula', models.CharField(blank=True, max_length=11, null=True, verbose_name='matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('cpf', models.CharField(max_length=14, verbose_name='cpf')),
                ('telefone', models.CharField(max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('matricula', models.CharField(blank=True, max_length=11, null=True, verbose_name='matricula')),
                ('materia', models.CharField(max_length=100, verbose_name='materia')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='sala_aula.Aluno', verbose_name='Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='sala_aula.Professor', verbose_name='Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome_turma')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='sala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='sala_aula.Turma', verbose_name='Turma'),
        ),
    ]
